# fly.toml file generated for polished-voice-3219 on 2023-04-11T21:48:34+02:00

app = "polished-voice-3219"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
